package com.timlee9024.crgltf.api.v0.impl;

import com.timlee9024.crgltf.gl.GL30Abstraction;
import com.timlee9024.crgltf.gl.GltfMaterialConverterPackManager;
import com.timlee9024.crgltf.gl.OpenGLObjectRefSet;
import com.timlee9024.crgltf.gl.constants.GltfMaterialToTextureConstants;
import com.timlee9024.crgltf.gl.constants.VanillaRenderConstants;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.DefaultDaxShaderRenderedMaterialModelCreator;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedGltfModel;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedGltfModelCreator;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedMeshModelCreator;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedMeshPrimitiveModelCreator;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedNodeModelCreator;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedSceneModel;
import com.timlee9024.crgltf.gl.rendered.daxshader.impl.GL21ExtDaxShaderRenderedSceneModelCreator;
import com.timlee9024.crgltf.gl.rendered.impl.CombinedRenderedTextureModelCreator;
import com.timlee9024.crgltf.gl.rendered.impl.DefaultGltfAnimationPlayer;
import com.timlee9024.crgltf.gl.rendered.impl.DefaultGltfAnimationPlayerCreator;
import com.timlee9024.crgltf.gl.rendered.impl.DefaultRenderedTextureModelCreator;
import de.javagl.jgltf.model.GltfModel;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraftforge.fml.client.SplashProgress;
import net.optifine.shaders.Shaders;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL12;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;

import java.util.Collection;

public class GL21ExtDaxShaderUniversalGltfRenderer extends RenderedUniversalGltfRenderer<GL21ExtDaxShaderRenderedGltfModel, DefaultGltfAnimationPlayer> {

	@Override
	protected GL21ExtDaxShaderRenderedGltfModel[] createRenderedGltfModelsArray(int length) {
		return new GL21ExtDaxShaderRenderedGltfModel[length];
	}

	@Override
	protected DefaultGltfAnimationPlayer[] createGltfAnimationPlayerArray(int length) {
		return new DefaultGltfAnimationPlayer[length];
	}

	@Override
	protected void setupGltfModelForRender(Collection<ListenerGroup> listenerGroups) {
		if (isFinishModLoading) {
			setupGltfModelForOptiFineRender(listenerGroups);
		} else {
			try {
				SplashProgress.pause(); //This prevents the container object generated by glGenVertexArrays during the game startup become invalid after SplashProgress#finish().
				setupGltfModelForOptiFineRender(listenerGroups);
			} finally {
				SplashProgress.resume(); //When any Exception throws, this is still need to be executed in order to proceed to game crash, otherwise the game will be hanged.
			}
		}
	}

	@Override
	public void render(int modelId, int scene) {
		GL11.glPushAttrib(GL11.GL_ALL_ATTRIB_BITS);

		//These render setup is required to match the default value of glTF spec.
		GL11.glDisable(GL11.GL_BLEND);
		GL11.glDisable(GL11.GL_ALPHA_TEST);
		GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
		GL11.glColor4f(1.0F, 1.0F, 1.0F, 1.0F); //The default value if COLOR_0 does not specify.

		int activeProgramID = Shaders.activeProgramID;
		GL21ExtDaxShaderRenderedSceneModel.currentGlProgram = activeProgramID;
		if (activeProgramID == 0) {
			//For render in vanilla fixed function pipeline.
			GL11.glEnable(GL12.GL_RESCALE_NORMAL); //In case of render as Entity.
			GL11.glEnable(GL11.GL_LIGHTING); //In case of render in GUI.
			GL11.glShadeModel(GL11.GL_SMOOTH);
			VanillaRenderConstants.getInstance().setupEmissiveTexEnv();

			renderedGltfModels[modelId].renderScene(scene);
		} else {
			renderedGltfModels[modelId].renderSceneForDaxShader(scene);
		}

		GL11.glPopAttrib();
	}

	protected void setupGltfModelForOptiFineRender(Collection<ListenerGroup> listenerGroups) {
		GL21ExtDaxShaderRenderedGltfModelCreator renderedGltfModelCreator = new GL21ExtDaxShaderRenderedGltfModelCreator();
		renderedGltfModelCreator.renderedSceneModelCreator = new GL21ExtDaxShaderRenderedSceneModelCreator();
		renderedGltfModelCreator.renderedNodeModelCreator = new GL21ExtDaxShaderRenderedNodeModelCreator();
		renderedGltfModelCreator.renderedNodeModelCreator.renderedMeshModelCreator = new GL21ExtDaxShaderRenderedMeshModelCreator();
		renderedGltfModelCreator.renderedNodeModelCreator.renderedMeshModelCreator.renderedMeshPrimitiveModelCreator = new GL21ExtDaxShaderRenderedMeshPrimitiveModelCreator();

		DefaultDaxShaderRenderedMaterialModelCreator renderedMaterialModelCreator = new DefaultDaxShaderRenderedMaterialModelCreator();
		renderedGltfModelCreator.renderedMaterialModelCreator = renderedMaterialModelCreator;
		renderedMaterialModelCreator.combinedRenderedTextureModelCreator = new CombinedRenderedTextureModelCreator();
		renderedMaterialModelCreator.renderedTextureModelCreator = new DefaultRenderedTextureModelCreator();

		renderedMaterialModelCreator.colorTextureProgram = GltfMaterialConverterPackManager.getInstance().getColorTextureProgram();
		renderedMaterialModelCreator.normalTextureProgram = GltfMaterialConverterPackManager.getInstance().getNormalTextureProgram();
		renderedMaterialModelCreator.specularTextureProgram = GltfMaterialConverterPackManager.getInstance().getSpecularTextureProgram();

		DefaultGltfAnimationPlayerCreator gltfAnimationPlayerCreator = new DefaultGltfAnimationPlayerCreator();

		GL11.glPushAttrib(GL11.GL_ALL_ATTRIB_BITS);
		GL11.glDisable(GL11.GL_BLEND);
		GL11.glDisable(GL11.GL_ALPHA_TEST);

		int currentFramebuffer = GL11.glGetInteger(GL30.GL_FRAMEBUFFER_BINDING);
		int currentProgram = GL11.glGetInteger(GL20.GL_CURRENT_PROGRAM);

		OpenGlHelper.glBindFramebuffer(OpenGlHelper.GL_FRAMEBUFFER, GltfMaterialToTextureConstants.getInstance().getGlCanvasFramebuffer());

		for (ListenerGroup listenerGroup : listenerGroups) {
			if (listenerGroup.compiledGltfModel == null) continue;
			renderedMaterialModelCreator.combinedRenderedTextureModelCreator.pixelDataLookup = renderedMaterialModelCreator.renderedTextureModelCreator.pixelDataLookup = listenerGroup.compiledGltfModel.getPixelDataLookup();
			renderedMaterialModelCreator.combinedRenderedTextureModelCreator.glTextures = renderedMaterialModelCreator.renderedTextureModelCreator.glTextures = new OpenGLObjectRefSet();
			renderedGltfModelCreator.renderedNodeModelCreator.renderedMeshModelCreator.renderedMeshPrimitiveModelCreator.glBuffers = renderedGltfModelCreator.glBuffers = new OpenGLObjectRefSet();
			renderedGltfModelCreator.renderedNodeModelCreator.renderedMeshModelCreator.renderedMeshPrimitiveModelCreator.glVertexArrays = renderedGltfModelCreator.glVertexArrays = new OpenGLObjectRefSet();
			GltfModel gltfModel = listenerGroup.compiledGltfModel.getGltfModel();
			gltfAnimationPlayers[listenerGroup.modelId] = gltfAnimationPlayerCreator.create(gltfModel, renderedGltfModels[listenerGroup.modelId] = renderedGltfModelCreator.create(gltfModel));
			GL30Abstraction.glBindVertexArray(0);
		}

		OpenGlHelper.glBindFramebuffer(OpenGlHelper.GL_FRAMEBUFFER, currentFramebuffer);
		GL20.glUseProgram(currentProgram);

		GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, 0);
		GL15.glBindBuffer(GL15.GL_ELEMENT_ARRAY_BUFFER, 0);

		GL11.glPopAttrib();
	}

}
